CREATE OR REPLACE PACKAGE PKG_PROFESSOR AS
    CURSOR CURSOR_TOTAL_TURMAS_PROFESSOR RETURN PROFESSORES%ROWTYPE;
    FUNCTION TOTAL_TURMAS_PROFESSOR(P_ID_PROFESSOR IN NUMBER) RETURN NUMBER;
    FUNCTION PROFESSOR_DA_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN VARCHAR2;
END PKG_PROFESSOR;

-- Implementação

CREATE OR REPLACE PACKAGE BODY PKG_PROFESSOR AS
    CURSOR CURSOR_TOTAL_TURMAS_PROFESSOR RETURN PROFESSORES%ROWTYPE IS
        SELECT P.* 
        FROM PROFESSORES P
        JOIN TURMAS T ON P.ID = T.ID_PROFESSOR
        GROUP BY P.ID, P.NOME
        HAVING COUNT(T.ID) > 1;

    FUNCTION TOTAL_TURMAS_PROFESSOR(P_ID_PROFESSOR IN NUMBER) RETURN NUMBER IS
        V_TOTAL NUMBER;
    BEGIN
        SELECT COUNT(*) INTO V_TOTAL
        FROM TURMAS
        WHERE ID_PROFESSOR = P_ID_PROFESSOR;
        RETURN V_TOTAL;
    END TOTAL_TURMAS_PROFESSOR;

    FUNCTION PROFESSOR_DA_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN VARCHAR2 IS
        V_NOME_PROFESSOR VARCHAR2(100);
    BEGIN
        SELECT P.NOME INTO V_NOME_PROFESSOR
        FROM PROFESSORES P
        JOIN DISCIPLINAS D ON P.ID = D.ID_PROFESSOR
        WHERE D.ID = P_ID_DISCIPLINA;
        RETURN V_NOME_PROFESSOR;
    END PROFESSOR_DA_DISCIPLINA;
END PKG_PROFESSOR;
