CREATE OR REPLACE PACKAGE PKG_ALUNO AS
    PROCEDURE EXCLUIR_ALUNO(P_ID_ALUNO IN NUMBER);
    CURSOR CURSOR_ALUNOS_MAIORES RETURN ALUNOS%ROWTYPE;
    CURSOR CURSOR_ALUNOS_POR_CURSO(P_ID_CURSO IN NUMBER) RETURN ALUNOS%ROWTYPE;
END PKG_ALUNO;


-- Implementação
CREATE OR REPLACE PACKAGE BODY PKG_ALUNO AS
    PROCEDURE EXCLUIR_ALUNO(P_ID_ALUNO IN NUMBER) IS
    BEGIN
        DELETE FROM MATRICULAS WHERE ID_ALUNO = P_ID_ALUNO;
        DELETE FROM ALUNOS WHERE ID = P_ID_ALUNO;
    END EXCLUIR_ALUNO;

    CURSOR CURSOR_ALUNOS_MAIORES RETURN ALUNOS%ROWTYPE IS
        SELECT * FROM ALUNOS
        WHERE TRUNC(MONTHS_BETWEEN(SYSDATE, DATA_NASC)/12) > 18;

    CURSOR CURSOR_ALUNOS_POR_CURSO(P_ID_CURSO IN NUMBER) RETURN ALUNOS%ROWTYPE IS
        SELECT A.* 
        FROM ALUNOS A
        JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
        WHERE M.ID_CURSO = P_ID_CURSO;
END PKG_ALUNO;
