CREATE OR REPLACE PACKAGE PKG_DISCIPLINA AS
    PROCEDURE CADASTRAR_DISCIPLINA(P_NOME IN VARCHAR2, P_DESCRICAO IN VARCHAR2, P_CARGA_HORARIA IN NUMBER);
    CURSOR CURSOR_TOTAL_ALUNOS_DISCIPLINAS RETURN DISCIPLINAS%ROWTYPE;
    CURSOR CURSOR_MEDIA_IDADE_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN NUMBER;
    PROCEDURE LISTAR_ALUNOS_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER);
END PKG_DISCIPLINA;

-- Implementação

CREATE OR REPLACE PACKAGE BODY PKG_DISCIPLINA AS
    PROCEDURE CADASTRAR_DISCIPLINA(P_NOME IN VARCHAR2, P_DESCRICAO IN VARCHAR2, P_CARGA_HORARIA IN NUMBER) IS
    BEGIN
        INSERT INTO DISCIPLINAS (NOME, DESCRICAO, CARGA_HORARIA)
        VALUES (P_NOME, P_DESCRICAO, P_CARGA_HORARIA);
    END CADASTRAR_DISCIPLINA;

    CURSOR CURSOR_TOTAL_ALUNOS_DISCIPLINAS RETURN DISCIPLINAS%ROWTYPE IS
        SELECT D.*
        FROM DISCIPLINAS D
        JOIN MATRICULAS M ON D.ID = M.ID_DISCIPLINA
        GROUP BY D.ID, D.NOME, D.DESCRICAO, D.CARGA_HORARIA
        HAVING COUNT(M.ID_ALUNO) > 10;

    CURSOR CURSOR_MEDIA_IDADE_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) RETURN NUMBER IS
        SELECT AVG(TRUNC(MONTHS_BETWEEN(SYSDATE, A.DATA_NASC)/12))
        FROM ALUNOS A
        JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
        WHERE M.ID_DISCIPLINA = P_ID_DISCIPLINA;

    PROCEDURE LISTAR_ALUNOS_DISCIPLINA(P_ID_DISCIPLINA IN NUMBER) IS
    BEGIN
        FOR REC IN (
            SELECT A.NOME
            FROM ALUNOS A
            JOIN MATRICULAS M ON A.ID = M.ID_ALUNO
            WHERE M.ID_DISCIPLINA = P_ID_DISCIPLINA
        ) LOOP
            DBMS_OUTPUT.PUT_LINE('Aluno: ' || REC.NOME);
        END LOOP;
    END LISTAR_ALUNOS_DISCIPLINA;
END PKG_DISCIPLINA;
